[build]
  base = "stare-ware"
  publish = "stare-ware/build"
  command = "cd stare-ware && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
